plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.144'
}

base {
    archivesName = mod_id
}

version = mod_version
group = mod_group_id

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neo_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files("libs/sable-companion-common-1.21.1-1.6.0.jar")
    compileOnly files("libs/sable-neoforge-1.21.1-2.0.3.jar")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}