org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

mod_id=sablecamera
mod_name=Sable Camera Anchor
mod_version=1.0.0
mod_group_id=dev.bapmain.sablecamera
mod_authors=bapmain
mod_license=MIT
mod_description=Minimal camera anchor for Sable / Create Aeronautics

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21.1.0,)
loader_version_range=[4,)